spring.datasource:
  url: 'jdbc:postgresql://127.0.0.1/satella'
  username: 'satella'
  password: '12345'
  driver-class-name: 'org.postgresql.Driver'
  dialect: 'org.hibernate.dialect.PostgreSQL92Dialect'
server:
  executor: 'Paper'
unregister-commands:
    - 'tell'
    - 'a'  
    - 'gamemode'
    - 'clear'
    - 'give'
    - 'about'
    - 'restart'
    - 'spigot'
    - 'reload'
    - 'rl'
    - 'msg'
    - 'help'
    - '?'
    - 'ver'
    - 'w'
    - 'version'
    - 'reload'
    - 'w'
    - 'tp'
    - 'list'
    - 'plugins'
    - 'pl'
    - 'god'
    - 'ungod'